version: '2'
services:
    ptah-app:
        image: ptah
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://ptah-postgresql:5432/PTAH
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=ptah-elasticsearch:9300
        ports:
            - 8080:8080
    ptah-postgresql:
        extends:
            file: postgresql.yml
            service: ptah-postgresql
    ptah-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: ptah-elasticsearch
